"use client";
import { FormEvent, useState } from "react";
const guides=[
{stage:"01",title:"Newly Licensed Agent",line:"TURN YOUR LICENSE INTO A CAREER",href:"https://www.canva.com/d/kBw7rrA0VshiAdt"},
{stage:"02",title:"Developing Agent",line:"BUILDING CONSISTENCY",href:"https://www.canva.com/d/TpqX8x9EPfdWv9k"},
{stage:"03",title:"Productive Agent",line:"BUILD A BUSINESS THAT WORKS FOR YOU",href:"https://www.canva.com/d/ggyF5J1gTgLIF80"},
{stage:"04",title:"Leadership",line:"BUILD YOUR MARKET",href:"https://www.canva.com/d/1TJ9wvclvHuwMIf"}];
export default function Home(){const[status,setStatus]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Sending…");const form=e.currentTarget;const response=await fetch("/api/join",{method:"POST",body:new FormData(form)});if(response.ok){form.reset();setStatus("Thank you. Mike will be in touch shortly.")}else setStatus("Something went wrong. Please try again.")}
return <><header className="siteHeader"><a className="azLogo" href="#home" aria-label="ADT Realty Arizona home"><span className="stateMark">AZ</span><span><strong>ADT</strong> REALTY<small>ARIZONA</small></span></a><nav><a className="active" href="#home">Home</a><a href="#buyers">Buy</a><a href="#sellers">Sell</a><a href="/heroes">Community Heroes</a><a href="#join">Join ADT</a></nav><a className="headerCta" href="#connect">Talk to an Expert <b>›</b></a><button className="search" aria-label="Search">⌕</button></header>
<main><section id="home" className="homeHero"><div className="heroVeil"/><div className="heroCenter"><h1>ADT REALTY — ARIZONA</h1><p>Local expertise. Modern tools. Relationships that matter.</p><div className="heroActions"><a className="solidButton" href="#buyers">Buy a Home <b>›</b></a><a className="outlineButton" href="#sellers">Sell a Home <b>›</b></a></div></div><div className="heroTag">ARIZONA<br/>HOMES.<br/>STRONGER<br/>TOGETHER.<i/></div></section>
<section className="values"><div className="valuesTitle"><i/><h2>Our Core Values</h2></div><div className="valueRow"><div><span>♙</span><b>Helping Others</b></div><div><span>♢</span><b>Do the Right Thing Every Time</b></div><div><span>♧</span><b>Build Relationships</b></div></div></section>
<section id="buyers" className="story buyerStory"><div className="storyImage buyerImage"><div className="imageLabel">THE RIGHT HOME STARTS<br/>WITH THE RIGHT PLAN.</div></div><div className="storyCopy"><i className="redRule"/><p className="kicker">BUYING IN ARIZONA</p><h2>Your Path to<br/>Homeownership Starts Here</h2><p>Buying a home is exciting. We’ll help you understand your options, prepare for each step, and move forward with confidence.</p><ul><li>Know what you can comfortably afford</li><li>Understand cash to close and financing choices</li><li>Follow a clear roadmap from planning to keys</li></ul><a className="solidButton" href="https://acebuyer.adtrealtyaz.com">Start My Homebuying Plan <b>›</b></a></div></section>
<section id="sellers" className="story sellerStory"><div className="storyCopy"><i className="redRule"/><p className="kicker lightKicker">SELLING IN ARIZONA</p><h2>Your Home Deserves<br/>a Real Strategy</h2><p>An online estimate cannot see what makes your home different. We’ll help you understand your market, prepare with purpose, and position your property to get results.</p><ul><li>Local pricing and positioning</li><li>A practical preparation plan</li><li>Marketing built around your property</li></ul><a className="outlineButton" href="#connect">Start My Selling Plan <b>›</b></a></div><div className="sellerStatement"><span>“</span><strong>The right price gets attention.<br/>The right strategy gets results.</strong></div></section>
<section id="join" className="joinSection"><div className="sectionHeading"><i/><p>JOIN ADT REALTY</p><h2>Where Are You in Your<br/>Real Estate Career?</h2><span>ADT Realty has the tools, technology, training and support to help you move forward—regardless of where you are today.</span></div><div className="guideGrid">{guides.map(g=><a key={g.stage} className="guideCard" href={g.href} target="_blank" rel="noreferrer"><em>{g.stage}</em><p>{g.line}</p><h3>{g.title}</h3><b>Explore the Presentation <span>›</span></b></a>)}</div><div className="joinCta"><h3>Ready to build what’s next?</h3><p>Have a confidential, no-pressure conversation about your goals and whether ADT Realty is the right fit.</p><a className="solidButton" href="#connect">Start the Conversation <b>›</b></a></div></section>
<section id="connect" className="connectSection"><div><i className="redRule"/><p className="kicker lightKicker">CONNECT WITH ADT REALTY</p><h2>Let’s Make Your<br/>Next Step Clear.</h2><p>Tell us where you are and what you’re working toward. You’ll hear directly from an experienced Arizona real estate professional.</p></div><form onSubmit={submit}><div className="twoFields"><label>First Name<input name="firstName" required/></label><label>Last Name<input name="lastName" required/></label></div><label>Email Address<input name="email" type="email" required/></label><label>Phone Number<input name="phone" type="tel"/></label><label>I’m Interested In<select name="interest" defaultValue="" required><option value="" disabled>Select one</option><option>Buying a home</option><option>Selling a home</option><option>Joining ADT Realty</option><option>Finding an Arizona agent</option></select></label><label>How Can We Help?<textarea name="message" rows={4}/></label><button className="solidButton" type="submit">Start the Conversation <b>›</b></button><p className="formStatus" role="status">{status}</p></form></section></main>
<footer><div className="azLogo footerLogo"><span className="stateMark">AZ</span><span><strong>ADT</strong> REALTY<small>ARIZONA</small></span></div><p>Do the right thing. Every time.</p><p>© 2026 ADT Realty · Equal Housing Opportunity</p></footer></>}
