"use client";
import { useState } from "react";
import "./hero.css";
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
export default function CommunityHeroes(){
 const [mode,setMode]=useState<"buy"|"sell"|"both">("buy"); const [buy,setBuy]=useState(500000); const [sell,setSell]=useState(500000); const [status,setStatus]=useState("");
 const reward=(mode==="buy"?buy:mode==="sell"?sell:buy+sell)*.007; const commission=(mode==="buy"?buy:mode==="sell"?sell:buy+sell)*.03;
 const scroll=()=>document.getElementById("community-hero-form")?.scrollIntoView({behavior:"smooth",block:"center"});
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus("Sending…");const form=e.currentTarget;const fd=new FormData(form);fd.set("leadType","Community Heroes Savings");fd.set("estimatedReward",money(reward));fd.set("calculatorMode",mode);fd.set("buyPrice",money(buy));fd.set("sellPrice",money(sell));try{const r=await fetch("/api/leads",{method:"POST",body:fd});setStatus(r.ok?"Thank you. An ADT Realty professional will be in touch.":"Please try again or contact ADT Realty directly.");if(r.ok)form.reset();}catch{setStatus("Please try again or contact ADT Realty directly.")}}
 return <main className="ch">
  <section className="chHero"><div className="chHeroShade"/><img className="chLogo" src="/community-heroes-logo.png" alt="ADT Realty Community Heroes"/><div className="chHeroCopy"><div className="kicker">ADT Realty Community Heroes Program</div><h1>You Serve<br/>Arizona.<br/>Let Us Serve You.</h1><h2>Save When You<br/>Buy or Sell.</h2><p>ADT Realty Community Heroes recognizes the people who serve, support and strengthen our communities with meaningful real estate savings.</p><div className="professions">Military & Veterans • Law Enforcement • Firefighters & EMS • Healthcare Workers • Educators & School Staff</div><div className="heroAction"><button onClick={scroll}>See My Hero Savings</button><small>No application.<br/>No red tape.</small></div></div></section>
  <section className="why"><div className="sectionHead"><div className="redKicker">Built Around Appreciation</div><h2>Why We Created<br/>Community Heroes</h2><p>The ADT Realty Community Heroes Program was created to recognize more of the people who make our communities stronger, safer, healthier and better educated.</p><i/></div><div className="reasons">{[["01","Service Is Bigger Than a Job Title","Communities are supported by more than the people in the most recognizable uniforms. ADT Realty recognizes the professionals and support staff who help schools, hospitals, public agencies and service organizations operate every day."],["02","No Applications. No Red Tape.","You should not have to complete a complicated application or navigate an unnecessary approval process to be appreciated. We designed the program to be simple, clear and straightforward."],["03","More Heroes Deserve Recognition","Our program includes military members, veterans, first responders, healthcare workers, educators, school employees and others whose service helps strengthen our communities."],["04","Meaningful Savings When You Move","When you buy or sell with a participating ADT Realty agent, Community Heroes Savings are our way of recognizing your service and saying thank you."]].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><div className="whyCall"><div><small>Our Way of Saying Thank You</small><h3>See What ADT Realty Community Heroes Savings May Be Available to You.</h3></div><button onClick={scroll}>See My Hero Savings</button></div></section>
  <section className="calc"><div className="sectionHead"><div className="redKicker">Your Service May Be Worth Real Savings</div><h2>How Much Could <span>You Save?</span></h2><p>Enter an estimated purchase or sale price to calculate your potential Community Heroes savings.</p><i/></div><div className="calcShell"><div className="controls"><label>What are you planning to do?</label><div className="tabs">{(["buy","sell","both"] as const).map(m=><button className={mode===m?"active":""} onClick={()=>setMode(m)} key={m}>{m==="both"?"Buy & Sell":m}</button>)}</div>{mode!=="sell"&&<Price label="Estimated Purchase Price" value={buy} set={setBuy}/>} {mode!=="buy"&&<Price label="Estimated Sale Price" value={sell} set={setSell}/>}<div className="formula"><p>Estimated real estate commission <b>3%</b></p><p>Estimated Hero Reward <b>0.7% of transaction price</b></p><p>Reward portion of 3% commission <b>Approximately 23.33%</b></p></div></div><div className="result"><small>Your Estimated Hero Reward</small><h3>{mode==="both"?"Estimated Combined Savings":mode==="sell"?"Estimated Selling Savings":"Estimated Buying Savings"}</h3><strong>{money(reward)}</strong><p>Calculated at 0.7% of the transaction price.</p><div className="break"><span>Estimated 3% commission <b>{money(commission)}</b></span></div><button onClick={scroll}>Get My Exact Savings Estimate</button><em>No obligation • No spam • Takes less than 30 seconds</em></div></div><p className="disclosure">This calculator provides an estimate for educational purposes only. Estimated Hero Rewards are calculated at 0.7% of the applicable transaction price and assume a 3% real estate commission. Actual savings, eligibility and program benefits may vary based on the transaction, representation, commission, location and applicable Community Heroes program terms.</p></section>
  <section id="community-hero-form" className="lead"><div className="leadCopy"><small>ADT Realty Community Heroes</small><h2>Heroes, <span>We Have Your Back.</span></h2><p>See what your service could save you when you buy or sell a home in Arizona.</p></div><div className="leadForm"><div className="leadFormIntro"><small>Private • No Obligation • Local Arizona Professional</small><h3>Get Your Personalized Hero Savings</h3></div><form onSubmit={submit}><label className="nameField"><span>Name</span><input name="name" autoComplete="name" placeholder="Your name" required/></label><label className="emailField"><span>Email</span><input name="email" type="email" autoComplete="email" placeholder="you@example.com" required/></label><label className="phoneField"><span>Phone <em>optional</em></span><input name="phone" type="tel" autoComplete="tel" placeholder="(480) 555-0123"/></label><label className="categoryField"><span>Community Hero Category</span><select name="profession" required defaultValue=""><option value="" disabled>Select your category</option><option>Military / Veteran</option><option>Law Enforcement</option><option>Firefighter / EMS</option><option>Healthcare</option><option>Educator / School Staff</option><option>Other Community Service</option></select></label><label className="planField"><span>I’m Planning To</span><select name="plan" value={mode} onChange={e=>setMode(e.target.value as "buy"|"sell"|"both")}><option value="buy">Buy a home</option><option value="sell">Sell a home</option><option value="both">Buy & Sell</option></select></label><button type="submit">Show Me My Hero Savings</button><p className="formPromise">No application • No spam • Your information stays private</p><div className="formStatus">{status}</div></form></div></section>
  <section className="commit"><div className="commitCopy"><small>Proudly Serving Those Who Serve</small><h2>ADT Realty Is Proud to Help <span>Arizona Heroes.</span></h2><p>At ADT Realty, we believe those who serve our country and our communities deserve exceptional service in return. Our participating Arizona agents are proud to help military members, veterans, law enforcement officers, firefighters, EMS professionals, healthcare professionals and educators understand the ADT Realty Community Heroes savings that may be available when buying or selling a home.</p><blockquote>“Serving Arizona heroes is more than a marketing campaign. It is a commitment shared by ADT Realty agents across the state.”</blockquote><div className="points"><b>✓ ADT Realty Community Heroes Program</b><b>✓ Arizona Statewide Coverage</b><b>✓ Experienced Local Real Estate Agents</b><b>✓ Honored to Serve Arizona Heroes</b></div></div><div className="leader heroBrandClose"><img src="/community-heroes-logo.png" alt="ADT Realty Community Heroes Program"/><strong>Community Heroes</strong><span>Serving Arizona's community heroes</span></div></section>
 </main>
}
function Price({label,value,set}:{label:string,value:number,set:(v:number)=>void}){return <div className="price"><label>{label}</label><div className="priceBox">$ <input value={value.toLocaleString()} onChange={e=>set(Math.min(2000000,Math.max(0,Number(e.target.value.replace(/\D/g,""))||0)))}/></div><input className="slider" type="range" min="100000" max="2000000" step="10000" value={Math.max(100000,value)} onChange={e=>set(Number(e.target.value))}/><div className="range"><span>$100K</span><span>$2M</span></div></div>}
